// Generated by gencpp from file imm/control.msg
// DO NOT EDIT!


#ifndef IMM_MESSAGE_CONTROL_H
#define IMM_MESSAGE_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imm
{
template <class ContainerAllocator>
struct control_
{
  typedef control_<ContainerAllocator> Type;

  control_()
    : mass_position(0.0)
    , thrust(0.0)
    , heave_force(0.0)
    , roll_torque(0.0)
    , pitch_torque(0.0)  {
    }
  control_(const ContainerAllocator& _alloc)
    : mass_position(0.0)
    , thrust(0.0)
    , heave_force(0.0)
    , roll_torque(0.0)
    , pitch_torque(0.0)  {
  (void)_alloc;
    }



   typedef double _mass_position_type;
  _mass_position_type mass_position;

   typedef double _thrust_type;
  _thrust_type thrust;

   typedef double _heave_force_type;
  _heave_force_type heave_force;

   typedef double _roll_torque_type;
  _roll_torque_type roll_torque;

   typedef double _pitch_torque_type;
  _pitch_torque_type pitch_torque;




  typedef boost::shared_ptr< ::imm::control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imm::control_<ContainerAllocator> const> ConstPtr;

}; // struct control_

typedef ::imm::control_<std::allocator<void> > control;

typedef boost::shared_ptr< ::imm::control > controlPtr;
typedef boost::shared_ptr< ::imm::control const> controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imm::control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imm::control_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace imm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'imm': ['/home/bo/dev/REMUS/src/imm/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::imm::control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imm::control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imm::control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imm::control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imm::control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imm::control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imm::control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3053511a874b6c53cc14542e24e79dc6";
  }

  static const char* value(const ::imm::control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3053511a874b6c53ULL;
  static const uint64_t static_value2 = 0xcc14542e24e79dc6ULL;
};

template<class ContainerAllocator>
struct DataType< ::imm::control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imm/control";
  }

  static const char* value(const ::imm::control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imm::control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 mass_position\n\
float64 thrust\n\
float64 heave_force\n\
float64 roll_torque\n\
float64 pitch_torque\n\
";
  }

  static const char* value(const ::imm::control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imm::control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mass_position);
      stream.next(m.thrust);
      stream.next(m.heave_force);
      stream.next(m.roll_torque);
      stream.next(m.pitch_torque);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imm::control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imm::control_<ContainerAllocator>& v)
  {
    s << indent << "mass_position: ";
    Printer<double>::stream(s, indent + "  ", v.mass_position);
    s << indent << "thrust: ";
    Printer<double>::stream(s, indent + "  ", v.thrust);
    s << indent << "heave_force: ";
    Printer<double>::stream(s, indent + "  ", v.heave_force);
    s << indent << "roll_torque: ";
    Printer<double>::stream(s, indent + "  ", v.roll_torque);
    s << indent << "pitch_torque: ";
    Printer<double>::stream(s, indent + "  ", v.pitch_torque);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMM_MESSAGE_CONTROL_H
